//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograAvanzada.Northwind.Products.Model
{
     using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class Product
    {
        int ProductID { get; set; }
        string ProductName { get; set; }
        Nullable<int> SupplierID { get; set; }
        Nullable<int> CategoryID { get; set; }
        string QuantityPerUnit { get; set; }
        Nullable<decimal> UnitPrice { get; set; }
        Nullable<short> UnitsInStock { get; set; }
        Nullable<short> UnitsOnOrder { get; set; }
        Nullable<short> ReorderLevel { get; set; }
        bool Discontinued { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
