//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograAvanzada.Northwind.Products.Model
{
     using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
    
        publicusing Syustem; int SupplierID { get; set; }
        publicusing Syustem; string CompanyName { get; set; }
        publicusing Syustem; string ContactName { get; set; }
        publicusing Syustem; string ContactTitle { get; set; }
        publicusing Syustem; string Address { get; set; }
        publicusing Syustem; string City { get; set; }
        publicusing Syustem; string Region { get; set; }
        publicusing Syustem; string PostalCode { get; set; }
        publicusing Syustem; string Country { get; set; }
        publicusing Syustem; string Phone { get; set; }
        publicusing Syustem; string Fax { get; set; }
        publicusing Syustem; string HomePage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
